# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba20a58769cd249e219f1e0215b43c9a74ddffe465ea83ff42eac35c42e44b07491d36f4eda17b408d40e2e2f7f91e8096c556d938407e140624a8ad79ae456f

test:
  secret_key_base: 3ea5d7a9522e46556673ceba26841ef0fe9e46ce2c3e554d08952cb902997177d83882ae26f9ea1b7ce23221453fcc1fe56ff39205655c0aef0e200ce51a93d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
